apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zzz3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zzz3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zzz3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zzz3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zzz3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mtkp-tenant/rhtap-demo-app/hacbs-test-project-zzz3@sha256:a926d353f3a36f6cbb048740a01898e68cbc1d2ece902c5cf282d8772fd46a49
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
