apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zzz3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mtkp-tenant/rhtap-demo-app/hacbs-test-project-zzz3@sha256:a926d353f3a36f6cbb048740a01898e68cbc1d2ece902c5cf282d8772fd46a49
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
